
export const En = Object.freeze({
    lang: 'Language',
    name: 'Name',
    loading: 'Loading data. Please wait...',
    yes: 'Yes',
    no: 'No',
    back: 'Back',
    view: 'View',
    confirm: 'Confirm',
    cancel: 'Cancel',
    close: 'Close',
    submit: 'Submit',
    add: 'Add',
    edit: 'Edit',
    complete: 'Complete',
    acknowledge: 'Acknowledge',
    revert: 'Revert',

    update: 'Update',
    delete: 'Delete',
    addTrain: 'Add Training',

    idpTitle: 'Individual Development Plan',
    ttlCareerAsp: 'Career Aspiration',
    phCareerAspiration: 'Where do I see myself in future...',
    save: 'Save',
    ttlStrength: 'Strength (Min 3 - Max 5)',
    noStrength: 'No strengths listed.',
    addStrength: 'Add Strength',
    updStrength: 'Update Strength',
    strength: 'Strength',
    phStrength: 'My strength is...',
    areaOfDev: 'Area of Development',
    ttlAreaOfDev: 'Area of Development (Min 1 - Max 2)',
    noAreaDev: 'No area of development listed.',
    addAreaOfDev: 'Add Area of Development',
    updAreaOfDev: 'Update Area of Development',
    phAreaOfDev: 'My area of development is...',
    ttlActionPlan: 'Action Plan (3 Action Plans Required)',
    noActionPlan: 'No action plans listed.',
    what: 'Action Plan',

    action: 'View',
    actionPlan: 'Action Plan',
    addActionPlan: 'Add Action Plan',
    updActionPlan: 'Update Action Plan',
    phActionPlan: 'My development action plan is...',
    stDate: 'Start Date',
    dueDate: 'Due Date',
    dateErrMsg: 'End date should not be less than start date.',
    dateErrMsgMn: 'Planned date of next meeting should not be less than meeting date.',
    how: 'How',
    selectHow: 'Select How',
    trainingName: 'Training Name',
    mentorName: 'Mentor/Coach',
    competencyType: 'Competency Type',
    selectType: 'Select Type',
    mobilityAssessment: 'Mobility Assessment',
    areYouFlexi: 'Are you flexible to be mobile',
    preferLoc: 'Are you willing to explore working in other locations',
    preferFunc: 'Are you willing to explore working in another function',
    why: 'Why',
    untilWhen: 'Until when',
    idpSubmitMsg1: 'Your IDP form will be submitted to',
    idpSubmitMsg2: 'for supervisor acknowledgement. Do you want to proceed?',

    textLimitMsg: 'You may write up to 300 characters.',


    idpHome: 'IDP Home',
    welcomeIDP: 'Welcome to your Individual Development Plan (IDP) page.',
    welcomePara: `This page enables you to discuss with your Manager and serves as a tool for you to 
    organize and target your professional and personal development.`,
    hbClick: `Click`,
    hbHere: 'here',
    hbView: 'to download and view the',
    hbBook: 'IDP handbook',
    hbUnderstanding: 'and new features for better understanding. You may also download the',
    hbCareerTool: 'Career Conversation Tool and User Guide',
    hbActivity: 'to help you with this activity.',
    idpLetsStart: `Let's get started.`,
    plsClick:' Please click ',
    completionGuide: 'to refer to the IDP Completion guideline.',
    

    myIDP: 'My IDP',
    idpReview: 'Review',
    myTeam: 'My Team',
    myMentee: 'My Mentee',
    newIDP: 'New',
    inProgress: 'In Progress',
    completed: 'Completed',

    chartClick: 'You may click on the segments in the chart to know details.',

    clickedItemHead_10: `10% - Learning from Structured Traning/Education`,
    clickedItemBody_10: `This method of learning enables employees to go for trainings or educational classes 
    to learn on a specific topic or skill.`,
    clickedItemEx_10: `Eg. Attend Negotiation skill training.`,

    clickedItemHead_20: `20% - Learning from Relationship`,
    clickedItemBody_20: `This learning method enables employees to learn through a mentor or coach.`,
    clickedItemEx_20: `Eg. Shadowing Coach/Mentor to learn a certain skill set.`,

    clickedItemHead_70: `70% - Learning from Experience`,
    clickedItemBody_70: `This learning method enables employees to learn through on the job experiences gained while performing it.`,
    clickedItemEx_70: `Eg. Assignment to a preferred job function to learn from it.`,

    startIDP: 'Start IDP',

    status_1: 'IDP Setting',
    status_2: 'Supervisor Acknowledgement',
    status_3: 'IDP Action Plan In Progress',
    status_4: 'IDP Completion',

    udpCareerAspSuccess: 'Career Aspiration Successfully Updated.',
    udpCareerAspFail: 'Failed To Update Career Aspiration.',

    addStrengthSuccess: 'Strength Successfully Added.',
    addStrengthFail: 'Failed To Add Strength.',
    updStrengthSuccess: 'Strength Successfully Updated.',
    updStrengthFail: 'Failed To Update Strength.',
    delStrengthSuccess: 'Strength Successfully Deleted.',
    delStrengthFail: 'Failed To Delete The Strength.',

    addAreaSuccess: 'Area of Development Successfully Added.',
    addAreaFail: 'Failed To Add Area of Development.',
    updAreaSuccess: 'Area of Development Successfully Updated.',
    updAreaFail: 'Failed To Update Area of Development.',
    delAreaSuccess: 'Area of Development Successfully Deleted.',
    delAreaFail: 'Failed To Delete The Area of Development.',

    addActionSuccess: 'Action Plan Successfully Added.',
    addActionFail: 'Failed To Add Action Plan.',
    updActionSuccess: 'Action Plan Successfully Updated.',
    updActionFail: 'Failed To Update Action Plan.',
    delActionSuccess: 'Action Plan Successfully Deleted.',
    delActionFail: 'Failed To Delete The Action Plan.',
    saveDraftMessage: 'IDP has been saved as draft.',
    addFeedbackMentor: 'Mentor feedback successfully submitted.',


    updActionOutcomeSuccess: 'Action Plan Outcome Successfully Updated.',
    updActionOutcomeFail: 'Failed To Update Action Plan Outcome.',

    updMobilitySuccess: 'Mobility Successfully Updated.',
    updMobilityFail: 'Failed To Update Mobility.',

    failToSubmit: 'Failed to Submit',
    careerFailErr: 'Career Aspiration is required.',
    strengthFailErr: 'Strength must be Min 3 - Max 5.',
    areaFailErr: 'Area of Development must be Min 1 - Max 2.',
    actionFailErr: '3 Action Plans required.',
    mobilityFailErr: 'All Mobility fields are required.',

    trainingAdded: 'Training Added.',
    plsAddTraining: 'Please add training (Min 1 - Max 5)',
    addTraining: 'Add Training',
    jobCluster: 'Job Cluster',
    jobFamily: 'Job Family',
    jobCompetency: 'Competency',
    noCompetencyMsg: 'No Competency Available at this time.',
    jobTrainingName: 'Training Name',
    addedTrainingMsg: 'This training has been added already.',
    noTraingMsg: `No Training Available at the moment. You may either select a different competency training 
    or you may change your type of Action Plan to 70% - Learning From Experience or 20% - Learning from Relationship.`,
    addMentee: 'Add Mentee Note (You may add up to 12 notes/sessions)',

    outcome: 'Outcome/Result',

    submitSupSuccessMsg: 'Successfully submitted to your Supervisor.',
    submitSupFailMsg: 'Failed To Submit To Your Supervisor.',

    nextReviewDate: 'Next Review Date',

    ackQues_1: 'Have you completed having a career conversation with',
    ackQues_2: 'if yes then you may proceed to acknowledge the form.',

    revertQues_1: 'Are you sure to revert the IDP form of',
    completeQues: 'Are you sure to complete your IDP form',

    completeIDPSucess: 'IDP Successfully Completed.',
    completeIDPFail: 'Failed To Complete IDP.',

    ackIDPSuccess: 'Successfully Acknowledged.',
    ackIDPFail: 'Failed To Acknowledge.',

    revertIDPSuccess: 'Successfully Reverted.',
    revertIDPFail: 'Failed To Revert.',
    errorMobilityMsg: 'Please specify the function.',
    copyActionPlan: 'Copy Action Plan',
    idpForm: 'IDP Form',
    actionNum: 'Action Plan',
    newAction: 'New Action',
    copyAction: 'Copy Action',
    actionPercent: 'Action/Percentage',
    toBeCompleteBy: 'To be completed by',
    toUpdateProgBy: 'To update progress by',
    toCompleteProgBy: 'To complete progress by',
    completeOn: 'Complete on',
    invalidLengthModalFbMentor: 'Character Limit!'
});

export const My = Object.freeze({
    lang: 'Bahasa',
    name: 'Nama',
    loading: 'Sila tunggu...',
    yes: 'Ya',
    no: 'Tidak',
    back: 'Kembali',
    view: 'Lihat',
    confirm: 'Pasti',
    cancel: 'Batal',
    close: 'Tutup',
    submit: 'Hantar',
    add: 'Tambah',
    edit: 'Sunting',
    complete: 'Selasai',
    acknowledge: 'Pengesahan',
    revert: 'Kembalikan',

    update: 'Kemas Kini',
    delete: 'Padam',
    addTrain: 'Tambah Latihan',

    idpTitle: 'Pelan Pembangunan Individu',
    ttlCareerAsp: 'Aspirasi Kerjaya',
    phCareerAspiration: 'Diri saya pada masa hadapan',
    save: 'Simpan',
    ttlStrength: 'Kekuatan (Min 3 - Maks 5)',
    noStrength: 'Tiada kekuatan disenaraikan.',
    addStrength: 'Tambah Kekuatan',
    updStrength: 'Kekuatan Kemas Kini',
    strength: 'Kekuatan',
    phStrength: 'Kekuatan saya ialah…',
    areaOfDev: 'Bahagian yang boleh diperbaiki',
    ttlAreaOfDev: 'Bahagian yang boleh diperbaiki (Min 1 - Maks 2)',
    noAreaDev: 'Tiada bahagian yang boleh diperbaiki disenaraikan.',
    addAreaOfDev: 'Tambah Bahagian yang boleh dipertingkatkan',
    updAreaOfDev: 'Bahagian yang boleh dipertingkatkan',
    phAreaOfDev: 'Bahagian yang boleh pertingkatkan adalah…',
    ttlActionPlan: 'Pelan Tindakan (3 Diperlukan)',
    noActionPlan: 'Tiada pelan tindakan disenaraikan.',
    what: 'Plan Tindakan',

    action: 'Lihat',
    actionPlan: 'Plan Tindakan',
    addActionPlan: 'Tambah Plan Tindakan',
    updActionPlan: 'Plan Tindakan Kemas Kini',
    phActionPlan: 'Pelan tindakan saya untuk pembangunan potensi diri adalah...',
    stDate: 'Tarikh Mula',
    dueDate: 'Tarikh Tamat',
    dateErrMsg: 'Tidak boleh kurang dari tarikh mula.',
    dateErrMsgMn: 'Tarikh plan tidak boleh kurang dari tarikh jumpa.',
    how: 'Bagaimana',
    selectHow: 'Pilih Bagaimana',
    trainingName: 'Aktiviti Latihan',
    mentorName: 'Mentor/Jurulatih',
    competencyType: 'Jenis Kecekapan',
    selectType: 'Pilih jenis',
    mobilityAssessment: 'Penilaian Mobiliti',
    areYouFlexi: 'Adakah anda fleksibel untuk',
    preferLoc: 'Adakah anda bersedia untuk menerokai peluang pekerjaan di lokasi lain',
    preferFunc: 'Adakah anda bersedia untuk menerokai peluang pekerjaan di fungsi lain',
    why: 'Kenapa',
    untilWhen: 'Sampai Bila',
    idpSubmitMsg1: 'Borang IDP anda akan dihantar kepada',
    idpSubmitMsg2: 'untuk Penyelia memberi pengiktirafan?',

    textLimitMsg: 'Anda boleh menulis sehingga 300 perkataan.',

    idpHome: 'Laman IDP',
    welcomeIDP: 'Selamat Datang ke halaman Pelan Pembangunan Diri (IDP) anda.',
    welcomePara: `Laman ini membolehkan anda berbincang dengan Penyelia anda berkenaan Pelan Pembagunan Diri anda.`,
    hbClick: 'Klik',
    hbHere: 'disini',
    hbView: 'untuk memuat turun dan melihat',
    hbBook: 'Buku Panduan IDP (IDP Handbook)',
    hbUnderstanding: 'dan ciri-ciri terbaru untuk pemahaman yang lebih baik. Anda juga boleh memuat turun alat',
    hbCareerTool: 'Perbualan Kerjaya (Career Conversation Tool) dan Panduan Pengguna',
    hbActivity: 'untuk membantu anda dalam melaksanakan aktiviti ini.',
    idpLetsStart: `Mari kita mulakan.`,
    plsClick: ' Sila klik ',
    completionGuide: 'untuk merujuk kepada garis panduan bagi melengkapkan IDP.',


    myIDP: 'IDP Saya',
    idpReview: 'Tindakan',
    myTeam: 'Pasukan Saya',
    newIDP: 'Baru',
    inProgress: 'Sedang dilaksanakan',
    completed: 'Selesai',

    chartClick: 'Anda boleh klik pada mana-mana bahagian di carta di atas untuk mengetahui butiran.',

    clickedItemHead_10: `10% - Belajar melalui latihan berstruktur/pendidikan`,
    clickedItemBody_10: `Teknik pembelajaran melalui kelas latihan atau pembelajaran ini membolehkan anggota mengetahui 
    dengan lebih lanjut mengenai sesuatu tajuk atau kemahiran.`,
    clickedItemEx_10: `Contoh: Menjalani kelas latihan untuk memperbaiki teknik berunding dengan pelanggan.`,

    clickedItemHead_20: `20% - Belajar melalui hubungan dengan orang lain`,
    clickedItemBody_20: `Teknik pembelajaran ini membolehkan anggota untuk belajar melalui seseorang atau mentor.`,
    clickedItemEx_20: `Contoh: Merujuk kepada Mentor untuk belajar sesuatu kemahiran tertentu.`,

    clickedItemHead_70: `70% - Belajar melalui pengalaman`,
    clickedItemBody_70: `Teknik pembelajaran ini membolehkan anggota belajar melalui pengalaman yang diperoleh ketika melaksanakan tugasan.`,
    clickedItemEx_70: `Contoh: Melakukan tugasan yang berkaitan dengan fungsi pekerjaan yang diminati.`,

    startIDP: 'Mulakan IDP',

    status_1: 'IDP Mula',
    status_2: 'Pengesahan Penyelia',
    status_3: 'IDP Plan Tidakan Sedang Dilaksanakan',
    status_4: 'IDP Selesai',

    udpCareerAspSuccess: 'Aspirasi Kerjaya berjaya dikemaskini.',
    udpCareerAspFail: 'Aspirasi Kerjaya gagal dikemaskini.',

    addStrengthSuccess: 'Kekuatan berjaya dikemaskini.',
    addStrengthFail: 'Kekuatan gagal dikemaskini.',
    updStrengthSuccess: 'Kekuatan berjaya dikemaskini.',
    updStrengthFail: 'Kekuatan gagal dikemaskini.',
    delStrengthSuccess: 'Kekuatan berjaya dihapus.',
    delStrengthFail: 'Kekuatan gagal dihapus.',

    addAreaSuccess: 'Ruang pembangunan berjaya dikemaskini.',
    addAreaFail: 'Ruang pembangunan gagal dikemaskini.',
    updAreaSuccess: 'Ruang pembangunan berjaya dikemaskini.',
    updAreaFail: 'Ruang pembangunan gagal dikemaskini.',
    delAreaSuccess: 'Ruang pembangunan berjaya dihapus.',
    delAreaFail: 'Ruang pembangunan gagal dihapus.',

    addActionSuccess: 'Pelan tindakan berjaya dikemaskini.',
    addActionFail: 'Pelan tindakan gagal dikemaskini.',
    updActionSuccess: 'Pelan tindakan berjaya dikemaskini.',
    updActionFail: 'Pelan tindakan gagal dikemaskini.',
    delActionSuccess: 'Pelan tindakan berjaya dihapus.',
    delActionFail: 'Pelan tindakan gagal dihapus.',
    saveDraftMessage: 'Defaf IDP berjaya disimpan.',
    addFeedbackMentor: 'Maklum Balas daripada mentor berjaya dihantar.',

    updActionOutcomeSuccess: 'Pelan tindakan hasilnya berjaya dikemaskini.',
    updActionOutcomeFail: 'Pelan tindakan hasilnya gagal dikemaskini.',

    updMobilitySuccess: 'Kesediaan pergerakan berjaya dikemaskini.',
    updMobilityFail: 'Kesediaan pergerakan gagal dikemaskini.',

    failToSubmit: 'Gagal dihantar',
    careerFailErr: 'Aspirasi kerjaya diperlukan.',
    strengthFailErr: 'Kekuatan haruslah Minima 3 – Maksima 5.',
    areaFailErr: 'Ruang pembangunan haruslah Minima 1 - Maksima 2.',
    actionFailErr: 'Pelan Tindakan hendaklah mempunyai 3 tindakan.',
    mobilityFailErr: 'Kesemua bidang Mobiliti diperlukan.',

    trainingAdded: 'Latihan dikemaskini.',
    plsAddTraining: 'Sila tambah aktiviti latihan (Minima 1 – Maksima 5)',
    addTraining: 'Tambah Latihan',
    jobCluster: 'Bidang Pekerjaan',
    jobFamily: 'Kumpulan Perkerjaan',
    jobCompetency: 'Kecekapan',
    noCompetencyMsg: 'Tiada Kecekapan berkaitan buat masa ini.',
    jobTrainingName: 'Nama Latihan',
    addedTrainingMsg: 'Latihan telah ditambah',
    noTraingMsg: `Tiada latihan berkaitan buat masa ini. Sila pilih tajuk kecekapan yang lain atau anda boleh menukar 
    jenis Pelan Tindakan anda kepada 70% - Belajar melalui pengalaman atau 20% - Belajar melalui hubungan dengan orang lain.`,
    addMentee: 'Tambah Nota Menti (Anda boleh tambah sehingga 12 nota/sesi)',


    outcome: 'Hasilnya',

    submitSupSuccessMsg: 'Berjaya dihantar kepada Penyelia Anda.',
    submitSupFailMsg: 'Gagal dihantar kepada Penyelia Anda.',

    nextReviewDate: 'Tarikh Perbincangan Semula',

    ackQues_1: 'Adakah anda telah selesai menjalankan perbualan kerjaya (Career Conversation) dengan',
    ackQues_2: 'Jika ya, sila teruskan ke pengesahan borang IDP.',

    revertQues_1: 'Adakah anda pasti untuk kembalikan borang IDP',
    completeQues: 'Adakah anda pasti untuk lengkapkan borang IDP',

    completeIDPSucess: 'Berjaya dilengkapkan.',
    completeIDPFail: 'Gagal dilengkapkan.',

    ackIDPSuccess: 'Berjaya dipengesahan.',
    ackIDPFail: 'Gagal dipengesahan.',

    revertIDPSuccess: 'Berjaya dikembalikan.',
    revertIDPFail: 'Gagal dikembalikan.',
    errorMobilityMsg: 'Sila perincikan fungsi yang dipilih.',
    copyActionPlan: 'Salin Pelan Tindakan',
    year: 'Tahun',
    actionNum: 'Pelan Tindakan',
    newAction: 'Tindakan Baru',
    copyAction: 'Salin Tindakan',
    actionPercent: 'Aksi/Peratus',
    toBeCompleteBy: 'Perlu diselesaikan sebelum',
    toUpdateProgBy: 'Perlu dikemaskini kemajuan sebelum',
    toCompleteProgBy: 'Perlu diselesaikan kemajuan sebelum',
    completeOn: 'Selesai pada',
    invalidLengthModalFbMentor: 'Aksara capai maksima!'
});
