export const EnLang = Object.freeze({

    goalSet: 'Goal Setting',
    fback: 'Feedback',
    lang: 'Language',
    searchBar: 'MAPS Year: ',
    searchBtn: 'GO',
    printPage: 'Print Page',
    evaluator: 'EVALUATOR',
    evaluator2: 'Appraiser',
    teamOverview: 'TEAM OVERVIEW',
    formTitle: 'MAPS EVALUATION FORM',
    empNameEv: 'EMPLOYEE NAME',
    mapsFormId: 'Form ID',
    statusForm: 'FORM STATUS',
    persInfo: 'PERSONAL INFORMATION',
    name: 'NAME',
    goalApp: 'Goal Approval',
    mYrRvwApp: 'Mid Year Review Appraisee',
    mYrRvwApper: 'Mid Year Review Appraiser',
    eYrRvwApp: 'Year End Review Appraisee',
    eYrRvwApper: 'Year End Review Appraiser',
    eYrRvwer: 'Year End Reviewer',
    eYrRvwerCheckBox: 'Year End Performance Rating',
    empAckw: 'Employee Acknowledgement',
    completed: 'Completed',
    email: 'EMAIL',
    phoneNo: 'PHONE NO.',
    descGolSet: 'You have minimum 3 Key Performance Indicators (KPI). [Reference Examples KPI]',
    descGolSet2: 'The total number of KPI must be in between 3 to 12 only. You can add/cancel/change KPI related to your work.',
    descGolSetSigInv: 'You can have 0-3 Key Performance Indicator (KPI) - if any.',
    descGolSetSigInv2: 'The total number of KPI can be between 0 to 3. (You can add/cancel/change aaccordingly).',
    jobRes: 'Job Responsibility',
    perspective: 'PERSPECTIVE',
    kpiCAP: 'KEY PERFORMANCE INDICATOR (KPI)',
    midYearTarget: 'MID-YEAR PERFORMANCE',
    yearTarget: 'YEAR END PERFORMANCE',
    minPers: 'Minimum Perspectives: 3',
    addBtn: 'Add',
    signInvolvmt: 'Significant Involvement',
    comment: 'Comment',
    enterGoalnMatric: 'Enter your Goals and Matrics below.',
    mainPerspective: 'Main Perspective',
    kpi: 'Key Performance Indicator',
    metricMeasure: 'Metric/Measure',
    weight: 'Weightage',
    target: 'Target',
    dueDate: 'Due Date',
    completion: 'Completion',
    deliverables: 'Deliverables',
    initiative: 'Initiative',
    competency: 'Competency',
    competencyLvl: 'Competency Level',
    subList: 'SUBORDINATES LIST',
    emptyMsg: 'List is empty!',
    view: 'View',
    golBtn: 'Goal',
    revertForm: 'Revert Subordinate Form',
    revertForm2: 'Revert form to Appraiser',
    invalidCharModal: '**Note: Please make sure target, weightage and metric are set.',
    invalidLengthModal: '**Note: Please make sure kpi is maximum 1000 characters',
    invalidLengthModalMt: '**Note: Please make sure metric/measure is maximum 200 characters',
    invalidValueModalWt: '**Note: Please make sure weightage is maximum 50',
    invalidCharModalDe: '**Note: Please make sure initiative and percent completion are set.',
    invalidLengthModalDe: '**Note: Please make sure initiative is maximum 100 characters',
    invalidLengthCmt: '**Note: Please make sure comment is minimum 50 and maximum 1000 characters',
    invalidLengthCmtAcknowledgement: '**Note: Please make sure comment is minimum 60 and maximum 1000 characters',
    appealNote: 'Appeal process can only be done once and the result will be considered as final.',
    remarkLengthError: '**Note: Please make sure revert message is maximum 160 characters',
    activity: 'Activity',
    achievement: 'Achievement',
    addInitiative: 'Add initiative',
    reminder: 'Reminder',
    twelweMax: 'Maximum KPI is 12 only.',
    threeMax: 'Maximum KPI is 3 only.',
    threeMin: 'Please make sure there are at least 3 KPI (1.0 Job Responsibility).',
    deleteConfJr: 'Your Appraiser will be notified of goal removal from your KPI. This action is not reversible and is subject to your Appraiser approval. Would you like to proceed',
    deleteConfSi: 'Your Appraiser will be notified of goal removal from your KPI. This action is not reversible and is subject to your Appraiser approval. Would you like to proceed',
    viewFbReq: 'Requested Feedback',
    addFb: 'Request Feedback',
    addFbOnBehalf: 'Request Feedback Representative',
    giveFb: 'Give Feedback',
    pendingFb: 'Pending Feedback',
    reqFbFrom: 'Request feedback from',
    errorStaffList: 'Please input more than 2 characters',
    to: 'To',
    from: 'From',
    myFb: 'My Feedback',
    myAct: 'My Activity',
    myAch: 'My Achievement',
    msg: 'Message',
    rating: 'Rating',
    pleaseWait: 'Please wait',
    viewFbSub: 'All Subordinates\' Feedback',
    viewActSub: 'All Subordinates\' Activity',
    viewAchSub: 'All Subordinates\' Achievement',
    result: 'Result',
    submitReqTo: 'Submit request to',
    ftfReminder: 'Face to Face session is required. Provide the rating, select check box and please give minimum 50 characters feedback to complete this process.',
    desc: 'Justification',
    empFb: 'Employee Feedback',
    supFb: 'Appraiser Feedback',
    errorMsgModalAppr: 'Please fill rating and feedback for rating 1 & 4 before proceed.',
    errorMsgModalApprResp: 'Please fill rating and your feedback is required.',
    errorMsgModalApprCC: 'Please fill rating before proceed.',
    revertComf: 'Send this form back to',
    revertCompleteMsg: 'Performance form is successfully revert back to',
    success: 'Success',
    submitSupvCompleteMsg: 'Performance form succesfully submitted to the supervisor. Please wait for your supervisor to approve your Performance form before proceeding',
    submitEmpCompleteMsg: 'Performance form is successfully submit to employee',
    submitEmpCompleteMsg2: 'Performance form successfully submitted',
    submitSupConf: 'You want to submit this form',
    approveEmpConf: 'You want to approve this form',
    approveEmpConfModal: 'Submit the Performance Form',
    compentencySubHeader: '*For rating 1 & 4, justification is required.',
    ratingPDF: 'View rating definition',
    ratReminder: 'Please make sure all rating and feedback is all complete.',
    viewProfile: 'View Personal Information',
    staffNo: 'Staff No.',
    div: 'DIVISION',
    company: 'COMPANY',
    gLib: 'Goal Library',
    gLibDetails: 'Select goal to add from the library. Click the icon to expand categories. You will be able to modify the goal in the next step.',
    yr: 'YEAR',
    currWith: 'CURRENTLY WITH',
    lastModify: 'LAST MODIFIED DATE',
    finalPerfRat: 'FINAL PERFORMANCE RATING',
    gSetp1: 'a. This worksheet is for employee’s Job Responsibility only. Job Responsibility refers to employee’s goals for the respective performance year.',
    gSetp2: 'b. Definition of Key Themes (Job Responsibility):',
    gSetp3: 'i. Customer: Any initiative that is related to the enhancement of customer experience for both internal & external customer. Example - TM Customer Satisfaction Index (TRIM)',
    gSetp4: 'ii. Business: Any initiative that is related to financial and business value creation of the company to achieve desired business goal. Example - TM Revenue (RM Mn)/ TM EBIT Growth (%)/ PIP',
    gSetp5: 'iii. People: Related to human capital development and productivity initiatives that contribute to the overall business performance. Example - Manpower Productivity Index',
    gSetp9: 'c. Definition of Key Themes (Significant Involvement):',
    gSetp10: 'i. Stretch Assignment: Additional assignment but still within the existing LOB / Division; ie: Agile Squad',
    gSetp11: 'ii. Cross Functional: Additional assignment or involvement not within the existing LOB / Division; ie: ILTM, Special Task Force',
    gSetp12: 'iii. Innovation: Innovation on the existing job; ie: process improvement',
    gSetp6: 'd. You may add New Goal or edit your Goal by click the Create New Goal button on top of this worksheet.',
    gSetp7: 'e. Please set your goals based on S.M.A.R.T 2x principles (SPECIFIC, MEASURABLE, ACHIEVABLE, RELEVANT, TIME BOUND).',
    gSetp8: 'f. Face to face session is required before this form can be sent to the next step.',
    gAppp1: 'This section is for assessing goal setting of your subordinatel (s). Please note that the goals must be in the SMART format with relevant task input. Ensure that face to face session has taken place before approving the form.',
    midYrAppp1: 'This section is for evaluating the accomplishments of your goal (s). Face to Face conversation is required. Please take note that there must be a rating for each goal before the form is sent to the next step.',
    midYrAprp1: 'This section is for evaluating the accomplishments of your subordinate. Please take note that there must be a rating for each goal. Ensure that face to face session has taken place before approving the form.',
    endYrAppp1: 'This section is for evaluating the accomplishments of your goal (s). Face to Face conversation is required. Please take note that there must be a rating for each goal before the form is sent to the next step.',
    endYrAprp1: 'This section is for evaluating the accomplishments of your subordinate. Please take note that there must be a rating for each goal. Ensure that face to face session has taken place before approving the form.',
    endYrRvewrp1: 'This section is to re-evaluate the accomplishments of your subordinate. Please take note that only the final rating is available for your action. Ensure you have taken into consideration the feedback given to the subordinate. Confirm Face to face session has taken place before the form is sent to the next step.',
    empAwkngmntp1: 'This section is for your acknowledgement of your performance (s). Kindly select either agree/disagree to the finalized performance rating.',
    empRating: 'Employee Rating',
    supRating: 'Supervisor Rating',
    saveBtn: 'Save',
    cancelBtn: 'Cancel',
    editBtn: 'Edit',
    deleteBtn: 'Delete',
    backBtn: 'Back',
    confirmBtn: 'Confirm',
    confirmation: 'Attention',
    hideBtn: 'Hide',
    yesBtn: 'Yes',
    noBtn: 'No',
    sendBtn: 'Send',
    ifAny: '(if any)',
    performanceRevw: 'PERFORMANCE REVIEW',
    viewDetail: 'View Detail',
    empPropos: 'Employee Proposed',
    sup1Propos: 'Appraiser Proposed',
    sup2Propos: 'Final Performance Rating by Reviewer',
    overallPerfRat: 'Overall Performance Rating',
    agreeBtn: 'Agree',
    disagreeBtn: 'Disagree',
    proceed: 'Proceed',
    completeAgree: 'I agree with performance rating that has been given to me.',
    completedisgree: 'Decline this performance rating? Your HCBD, Appraiser and Reviewer will be notified for any further action.',
    confirmationDisagree: 'Decline this performance rating? Your HCBD, Appraiser and Reviewer will be notified for any further action.',
    supOneAppraiser: 'Appraiser',
    supTwoReviewer: 'Reviewer',
    overallAppraisee: 'Overall Comments by Appraisee',
    overallAppraiser: 'Overall Comments by Appraiser',
    overallReviewer: 'Overall Comments by Reviewer',
    midYear: 'Mid Year',
    yearEnd: 'Year End',
    checkboxftf1: 'I hereby inform that the',
    checkboxftf2: 'been discussed based on face-to-face sessions.',
    checkboxftf3: 'I hereby confirm that the employee has been informed on the appeal result.',
    afterAppeal: 'After Appeal',
    error: 'OPPS!',
    kpiRat1: 'BELOW EXPECTATION',
    kpiRat2: 'MEETING EXPECTATION',
    kpiRat3: 'ABOVE EXPECTATION',
    kpiRat4: 'FAR EXCEED EXPECTATION',
    compRat1: 'LESS SATISFACTORY',
    compRat2: 'SATISFACTORY',
    compRat3: 'GOOD',
    compRat4: 'VERY GOOD',
    finalRat1: 'LESS SATISFACTORY',
    finalRat2: 'SATISFACTORY',
    finalRat3: 'VERY SATISFACTORY',
    finalRat4: 'EXCELLENT',
    remark: 'Comment',
    revertMsg: 'Revert Message',
    charError: 'Character is too long. Please enter maximum of 160 characters only.',
    remarkError: 'Please inset revert message',
    action: 'Action',
    addActivity: 'Add Activity',
    addAchievement: 'Add Achievement',
    details: 'Details',
    title: 'Title',
    uploadFile: 'Upload File',
    tooltipReqFb: 'This is the feedback that you requested from other person.',
    tooltipFbSub: 'This is the list of requested feedback to other person from all of your subordinates.',
    tooltipmyFb: 'The feedbacks received.',
    tooltipPendingFb: 'This is feedback that you requested.',
    fileAttch: 'Upload file/image',
    fileAttch2: 'Maximum attachment is 3 for each activity (JPG, JPEG, PNG, GIF and PDF). Size for each attachment cannot exceed 1MB.',
    fileAttchErr1: 'Maximum for each file/image is 1MB.',
    fileAttchErr2: 'Maximum 3 file/image per activity.',
    tooltipActivity: 'List of activities for employees.',
    tooltipAchievement: 'List of achievements for employees.',
    tooltipActivitySup: 'This is the list of activities for all of your subordinates.',
    tooltipAchievementSup: 'This is the list of achievements for all of your subordinates.',
    deleteConfActivity: 'Are you sure want to delete this activity',
    deleteConfAchievement: 'Are you sure want to delete this achievement',
    kpiLink: 'Link to KPI',
    createdOn: 'Created on',
    insert: 'insert',
    invalidTgtWt: 'Invalid format: Target and Weightage is in number only.',
    placeholdeKpi: 'Select one from below',
    errKpiActAch: 'KPI link is required.',
    pending: 'Pending',
    complete: 'Complete',
    noKpi: 'Not related'
});