export const MyLang = Object.freeze({

    goalSet: 'Penetapan Sasaran',
    fback: 'Maklum balas',
    lang: 'Bahasa',
    searchBar: 'MAPS Tahun: ',
    searchBtn: 'CARI',
    printPage: 'Cetak Halaman',
    evaluator: 'PENILAI',
    evaluator2: 'Penilai',
    teamOverview: 'TINJAUAN PASUKAN',
    formTitle: 'BORANG PENILAIAN MAPS',
    empNameEv: 'NAMA ANGGOTA',
    mapsFormId: 'ID Borang',
    statusForm: 'STATUS BORANG',
    persInfo: 'MAKLUMAT PERIBADI',
    name: 'NAMA',
    goalApp: 'Kelulusan Sasaran',
    mYrRvwApp: 'Penilaian Pertengahan Tahun Anggota',
    mYrRvwApper: 'Penilaian Pertengahan Tahun Penilai',
    eYrRvwApp: 'Penilaian Akhir Tahun Anggota',
    eYrRvwApper: 'Penilaian Akhir Tahun Penilai',
    eYrRvwer: 'Penilaian Akhir Tahun Penilai Semula',
    eYrRvwerCheckBox: 'Penilaian Akhir Tahun Penilai Semula',
    empAckw: 'Persetujuan Anggota',
    completed: 'Selesai',
    email: 'EMAIL',
    phoneNo: 'NO. TELEFON',
    descGolSet: 'Anda mempunyai 3 Petunjuk Prestasi Utama (PPU). [Contoh Rujukan PPU]',
    descGolSet2: 'Jumlah keseluruhan PPU mestilah diantara 3 sehingga 12 sahaja. Anda boleh tambah/batal/ubah PPU yang berkaitan dengan kerja anda.',
    descGolSetSigInv: 'Anda boleh mempunyai 0-3 Petunjuk Prestasi Utama (PPU) - jika ada.',
    descGolSetSigInv2: 'Jumlah keseluruhan PPU mestilah diantara 0 sehingga 3 sahaja. (Anda boleh tambah/batal/ubah mengikut keperluan).',
    jobRes: 'Kerja Hakiki',
    perspective: 'PERSPEKTIF',
    kpiCAP: 'PETUNJUK PRESTASI UTAMA (PPU)',
    midYearTarget: 'PENILAIAN PERTENGAHAN TAHUN',
    yearTarget: 'PRESTASI AKHIR TAHUN',
    minPers: 'Perspektif Minima: 3',
    addBtn: 'Tambah',
    signInvolvmt: 'Penglibatan Luar Kerja Hakiki',
    comment: 'Komen',
    enterGoalnMatric: 'Isikan Sasaran dan Metrik anda dibawah.',
    mainPerspective: 'Perspektif Utama',
    kpi: 'Petunjuk Prestasi Utama',
    metricMeasure: 'Metrik/Ukuran',
    weight: 'Pemberat',
    target: 'Sasaran',
    dueDate: 'Tarikh Akhir',
    completion: 'Selesai',
    deliverables: 'Penyampaian',
    initiative: 'Inisiatif',
    competency: 'Kompetensi',
    competencyLvl: 'Tahap Kompetensi',
    subList: 'SENARAI ANGGOTA',
    emptyMsg: 'Tiada data!',
    view: 'Lihat',
    golBtn: 'Sasaran',
    revertForm: 'Kembalikan Borang Anggota',
    revertForm2: 'Kembalikan borang kepada Penilai',
    invalidCharModal: '**Nota: Sila pastikan sasaran, pemberat dan matrik telah ditetapkan.',
    invalidLengthModal: '**Nota: Sila pastikan ppu tidak melebihi 1000 aksaran.',
    invalidLengthModalMt: '**Nota: Sila pastikan metrik/ukuran tidak melebihi 200 aksaran.',
    invalidValueModalWt: '**Nota: Sila pastikan pemberat tidak melebihi 50.',
    invalidCharModalDe: '**Nota: Sila pastikan inisiatif dan peratus selesai telah ditetapkan.',
    invalidLengthModalDe: '**Nota: Sila pastikan inisiatif tidak melebihi 100 aksaran.',
    invalidLengthCmt: '**Nota: Sila pastikan komen tidak kurang 50 dan tidak melebihi 1000 aksara.',
    invalidLengthCmtAcknowledgement: '**Nota: Sila pastikan komen tidak kurang dari 60 aksara.',
    appealNote: 'Proses rayuan hanya boleh dilakukan sekali sahaja dan keputusan selepas rayuan adalah muktamad.',
    remarkLengthError: '**Note: Sila pastikan ucapan pulang tidak melebihi 160 aksara.',
    activity: 'Aktiviti',
    achievement: 'Pencapaian',
    addInitiative: 'Tambah inisiatif',
    reminder: 'Peringatan',
    twelweMax: 'Maksimum 12 PPU sahaja.',
    threeMax: 'Maksimum 3 PPU sahaja.',
    threeMin: 'Sila pastikan terdapat sekurang-kurangnye 3 PPU (1.0 Kerja Hakiki).',
    deleteConfJr: 'Penilai anda akan diberitahu berkaitan PPU yang telah dibuang oleh anda. Tindakan ini tidak boleh ditukar semula dan tertakluk kepada kelulusan penilai anda. Adakah anda mahu meneruskan proses ini',
    deleteConfSi: 'Penilai anda akan diberitahu berkaitan PPU yang telah dibuang oleh anda. Tindakan ini tidak boleh ditukar semula dan tertakluk kepada kelulusan penilai anda. Adakah anda mahu meneruskan proses ini',
    viewFbReq: 'Maklum Balas Dipohon',
    addFb: 'Mohon Maklum Balas',
    addFbOnBehalf: 'Wakil Memohon Maklum Balas',
    giveFb: 'Beri Maklum Balas',
    pendingFb: 'Maklum Balas Perlu Dilengkapkan',
    reqFbFrom: 'Mohon maklum balas dari',
    errorStaffList: 'Pastikan input melebihi 2 karakter',
    to: 'Kepada',
    from: 'Daripada',
    myFb: 'Maklum Balas Saya',
    myAct: 'Aktiviti Saya',
    myAch: 'Pencapaian Saya',
    msg: 'Pesanan',
    rating: 'Penilaian',
    pleaseWait: 'Sila tunggu',
    viewFbSub: 'Semua Maklum Balas Anggota',
    viewActSub: 'Semua Aktiviti Anggota',
    viewAchSub: 'Semua Pencapaian Anggota',
    result: 'Keputusan',
    submitReqTo: 'Hantar permohonan kepada',
    ftfReminder: 'Sila selesaikan sesi bersemuka. Berikan penilaian, klik tanda pada kotak dan masukkan minima 50 aksara maklum balas untuk melengkapkan proses ini.',
    desc: 'Justifikasi',
    empFb: 'Komen Anggota',
    supFb: 'Komen Penilai',
    errorMsgModalAppr: 'Pastikan penilaian dan maklum balas diisi sebelum meneruskan proses. Justifikasi diperlukan bagi penilaian tahap 1 & 4.',
    errorMsgModalApprResp: 'Pastikan penilaian dan maklum balas diisi sebelum meneruskan proses.',
    errorMsgModalApprCC: 'Pastikan penilaian diisi sebelum meneruskan proses.',
    revertComf: 'Pulangkan borang ini semula kepada',
    revertCompleteMsg: 'Borang penilaian telah berjaya dikembalikan kepada',
    success: 'Berjaya',
    submitSupvCompleteMsg: 'Borang penilaian telah berjaya dihantar kepada penilai. Sila tunggu sehingga penilai meluluskan borang penilaian sebelum meneruskan proses seterusnya',
    submitEmpCompleteMsg: 'Borang penilaian telah berjaya dihantar kepada anggota',
    submitEmpCompleteMsg2: 'Borang penilaian telah berjaya dihantar kepada Penilai Semula',
    submitSupConf: 'Adakah anda pasti untuk menghantar borang penilaian ini',
    approveEmpConf: 'Adakah anda pasti untuk meluluskan borang penilaian ini',
    approveEmpConfModal: 'Adakah anda pasti untuk meluluskan borang penilaian ini',
    ratReminder: 'Pastikan semua penilaian dan maklum balas diisi sepenuhnya.',
    viewProfile: 'Lihat Maklumat Peribadi',
    compentencySubHeader: '*Pastikan justifikasi dilengkapkan bagi penilaian tahap 1 & 4.',
    staffNo: 'No. Staff',
    div: 'BAHAGIAN',
    company: 'SYARIKAT',
    gLib: 'Pustaka Sasaran',
    gLibDetails: 'Pilih sasaran untuk ditambah dari pustaka sasaran ini. Tekan ikon untuk besarkan kategori. Anda boleh ubah sasaran ini untuk langkah seterusnya.',
    yr: 'TAHUN',
    currWith: 'SEKARANG BERSAMA',
    lastModify: 'TARIKH TERAKHIR PERTUKARAN',
    finalPerfRat: 'PENILAIAN PRESTASI KESELURUHAN',
    gSetp1: 'a. Ruangan ini bertujuan untuk anggota memasukkan Tanggungjawab Kerjaya masing-masing. Tanggungjawab Kerjaya merujuk kepada Petunjuk Prestasi Utama dan Tugasan yang perlu dilakukan untuk mencapai PPU tersebut dalam tahun prestasi ini.',
    gSetp2: 'b. Penerangan Perspektif (Kerja Hakiki):',
    gSetp3: 'i. Pelanggan: Sebarang inisiatif yang berkaitan dengan menambah baik pengalaman pelanggan dalaman dan luaran. Contoh: Survey / Kadar kepuasan pelanggan',
    gSetp4: 'ii. Perniagaan: Sebarang inisiatif berkaitan dengan bidang kewangan dan mencipta nilai baru perniagaan untuk mencapai matlamat perniagaan. Contoh- Pendapatan / Penjimatan yang telah dijalankan',
    gSetp5: 'iii. Anggota:  Berkaitan dengan inisiatif perkembangan modal insan dan produktiviti yang menyumbang kepada prestasi perniagaan secara keseluruhan. Contoh - jumlah latihan yang dijalankan',
    gSetp9: 'c. Penerangan Perspektif (Penglibatan Luar Kerja Hakiki):',
    gSetp10: 'i. Tugasan Tambahan: Tugasan tambahan tetapi masih dalam LOB / Bahagian yang sama; ie: Agile Squad.',
    gSetp11: 'ii. Fungsi Bersilang: Penglibatan luar kerja hakiki melibatkan LOB / Bahagian lain ie ILTM, Projek Khas.',
    gSetp12: 'iii. Inovasi:  Inovasi bagi kerja hakiki ie: penambahbaikan proses kerja.',
    gSetp6: 'd. Anda bebas untuk menambah Petunjuk Prestasi Utama baru atau mengubah PPPU. Mulakan dengan mengetik butang TAMBAH pada setiap seksyen.',
    gSetp7: 'e. Sila tetapkan Petunjuk Prestasi Utama anda mengikut format SMART x2 (Tepat, Boleh dikira, Boleh dicapai, Berkaitan dan Mengikut Masa).',
    gSetp8: 'f. Sesi bersemuka perlu dijalankan sebelum borang ini dihantar ke langkah berikutnya.',
    gAppp1: 'Bahagian ini adalah untuk penilaian penetapan sasaran anggota di bawah seliaan anda. Sasaran mestilah ditetapkan mengikut prinsip SMART serta dengan tugasan yang berkaitan. Sila pastikan sesi perbincangan secara bersemuka (‘face to face’) diadakan sebelum meluluskan borang penilaian.',
    midYrAppp1: 'Bahagian ini adalah untuk penilaian pencapaian sasaran anda. Perbincangan secara bersemuka (‘face to face’) harus diadakan. Pastikan setiap sasaran telah dinilai sebelum menghantar borang penilaian ke langkah seterusnya.',
    midYrAprp1: 'Bahagian ini adalah untuk menilai pencapaian anggota di bawah seliaan anda. Pastikan setiap sasaran telah dinilai. Perbincangan secara bersemuka (‘face to face’) harus diadakan sebelum menghantar borang penilaian ke langkah seterusnya.',
    endYrAppp1: 'Bahagian ini adalah untuk menilai pencapaian sasaran anda. Perbincangan secara bersemuka (‘face to face’) harus diadakan. Pastikan setiap sasaran telah dinilai sebelum menghantar borang penilaian ke langkah seterusnya.',
    endYrAprp1: 'Bahagian ini adalah untuk menilai pencapaian anggota di bawah seliaan anda. Pastikan setiap sasaran telah dinilai. Perbincangan secara bersemuka (‘face to face’) harus diadakan sebelum menghantar borang penilaian ke langkah seterusnya',
    endYrRvewrp1: 'Bahagian ini  adalah untuk menilai semula pencapaian anggota di bawah seliaan anda. Anda hanya boleh membuat penilaian peringkat akhir. Pastikan anda telah mengambil kira maklum balas yang diberikan kepada anggota di bawah seliaan anda. Pastkan juga sesi perbincangan secara bersemuka (‘face to face’) telah diadakan sebelum menghantar borang penilaian ke langkah seterusnya.',
    empAwkngmntp1: 'Bahagian ini adalah untuk pengakuan penilaian prestasi anda. Sila pilih sama ada anda bersetuju / tidak bersetuju dengan penilaian prestasi akhir anda.',
    empRating: 'Penilaian Anggota',
    supRating: 'Penilaian Penilai',
    saveBtn: 'Simpan',
    cancelBtn: 'Batal',
    editBtn: 'Ubah',
    deleteBtn: 'Padam',
    backBtn: 'Kembali',
    confirmBtn: 'Setuju',
    confirmation: 'Perhatian',
    proceed: 'Teruskan',
    hideBtn: 'Tutup',
    yesBtn: 'Ya',
    noBtn: 'Tidak',
    sendBtn: 'Hantar',
    ifAny: '(jika ada)',
    performanceRevw: 'PENILAIAN PRESTASI',
    viewDetail: 'Lihat Perincian',
    empPropos: 'Penilaian Kendiri Anggota',
    sup1Propos: 'Penilaian dari Penilai',
    sup2Propos: 'Penilaian prestasi keseluruhan dari Penilai Semula',
    overallPerfRat: 'Penilaian Prestasi Keseluruhan',
    agreeBtn: 'Setuju',
    disagreeBtn: 'Tidak Setuju',
    completeAgree: 'Saya bersetuju dengan penilaian prestasi yang telah diberikan.',
    completedisgree: 'Adakah anda ingin menolak penilaian prestasi ini? Pihak HCBD, Penilai dan Penilai Semula akan dimaklumkan untuk tindakan selanjutnya.',
    supOneAppraiser: 'Penilai',
    supTwoReviewer: 'Penilai Semula',
    ratingPDF: 'Lihat definisi penilaian',
    afterAppeal: 'Selepas Rayuan',
    overallAppraisee: 'Komen Keseluruhan daripada Anggota',
    overallAppraiser: 'Komen Keseluruhan daripada Penilai',
    overallReviewer: 'Komen Keseluruhan daripada Penilai Semula',
    midYear: 'Pertengahan Tahun',
    yearEnd: 'Akhir Tahun',
    checkboxftf1: 'Saya dengan ini memaklumkan bahawa',
    checkboxftf2: 'ini telah dibincangkan berdasarkan pertemuan bersemuka.',
    checkboxftf3: 'Saya dengan ini mengesahkan bahawa anggota telah dimaklumkan tentang keputusan selepas rayuan',
    error: 'MOHON MAAF!',
    kpiRat1: 'TIDAK MENCAPAI SASARAN',
    kpiRat2: 'MENCAPAI SASARAN',
    kpiRat3: 'MELEBIHI SASARAN',
    kpiRat4: 'JAUH MELEBIHI SASARAN',
    compRat1: 'KURANG MEMUASKAN',
    compRat2: 'MEMUASKAN',
    compRat3: 'BAIK',
    compRat4: 'SANGAT BAIK',
    finalRat1: 'KURANG MEMUASKAN',
    finalRat2: 'MEMUASKAN',
    finalRat3: 'SANGAT MEMUASKAN',
    finalRat4: 'CEMERLANG',
    remark: 'Komen',
    revertMsg: 'Mesej dikembalikan',
    charError: 'Karakter terlalu panjang. Sila masukkan maksimum 160 aksara sahaja.',
    remarkError: 'Sila isikan komen pulangan',
    action: 'Tindakan',
    addActivity: 'Tambah Aktiviti',
    addAchievement: 'Tambah Pencapaian',
    details: 'Perincian',
    title: 'Tajuk',
    uploadFile: 'Muat Naik Fail',
    tooltipReqFb: 'Senarai rekod maklum balas yang dipohon.',
    tooltipFbSub: 'Ini ialah senarai permohonan maklum balas kepada orang lain daripada semua anggota anda.',
    tooltipmyFb: 'Maklum balas yang diterima.',
    tooltipPendingFb: 'Senarai maklum balas yang perlu dilengkapkan.',
    fileAttch: 'Muat naik fail/gambar',
    fileAttch2: 'Maksima lampiran adalah 3 bagi setiap aktiviti (JPG,JPEG, PNG, GIF dan PDF sahaja ). Saiz setiap lampiran tidak melebihi 1MB.',
    fileAttchErr1: 'Maksima setiap fail/gambar ialah 1MB.',
    fileAttchErr2: 'Maksima 3 fail/gambar bagi setiap aktiviti.',
    tooltipActivity: 'Senarai aktiviti anggota.',
    tooltipAchievement: 'Senarai pencapaian anggota.',
    tooltipActivitySup: 'Ini ialah senarai aktiviti untuk semua anggota anda.',
    tooltipAchievementSup: 'Ini ialah senarai pencapaian untuk semua anggota anda.',
    deleteConfActivity: 'Adakah anda ingin memadam aktiviti ini',
    deleteConfAchievement: 'Adakah anda ingin memadam pencapaian ini',
    kpiLink: 'Pautan pada PPU',
    createdOn: 'Dibuat pada',
    insert: 'Masukkan',
    invalidTgtWt: 'Format tidak sah: Sasaran dan pemberat hanya dalam nombor sahaja.',
    placeholdeKpi: 'Pilih satu dibawah',
    errKpiActAch: 'Pautan pada PPU ialah diperlukan.',
    pending: 'Belum Selesai',
    complete: 'Selesai',
    noKpi: 'Tidak berkaitan'
});