export const MapsVars = Object.freeze({
    
    //import
    GETImg: '/get/image/',
    
    //common
    GETKeyTheme: '/maps/common/get_key_theme/',
    POSTBasicInfo: '/maps/common/get_basicInfo',
    GETSubordinates: '/maps/common/get_subordinates',
    POSTGetSearchStaffByStaffId: '/maps/common/search_staff',
    GETProgressBar: '/maps/common/get_progress_bar',

    //employee
    POSTJobRes: '/maps/employee/save_job_resp',
    GETJobRes: '/maps/employee/get_job_resp_by_seq',
    GETEvaluationForm: '/maps/employee/get_eval_form/',
    GETFormList: '/maps/employee/get_form_list/',
    POSTSignificantInv: '/maps/employee/save_sgfnt_involv',
    POSTCommentEv: '/maps/employee/send_to_supv',
    POSTDeleteJobRes: '/maps/employee/delete_job_resp',
    GETJobResBySeq: '/maps/employee/get_job_resp_by_fmid_n_seq/',
    POSTDeleteSigInv: '/maps/employee/delete_sgfnt_involv',
    GETSigInvBySeq: '/maps/employee/get_sgfnt_involv_by_fmid_n_seq/',
    POSTRequestFeedback: '/maps/employee/request_feedback',
    GETViewFeedbackRequest: '/maps/employee/get_feedback_list_by_rpn/',
    GETViewFeedbackGiver: '/maps/employee/get_feedback_list_by_gpn/',
    POSTGiveFeedback: '/maps/employee/give_feedback',
    GETCompetencyList: '/maps/employee/get_competency_list/',
    POSTGetMidYearAppraisee: '/maps/employee/get_midyear_appraise_by_fmid_seq_n_type',
    POSTGetEndYearAppraisee: '/maps/employee/get_yearend_appraise_by_fmid_seq_n_type',
    POSTPostMidYearAppraisee: '/maps/employee/save_midyear_appraise',
    POSTPOSTEndYearAppraisee: '/maps/employee/save_yearend_appraise',
    POSTSupvRev: '/maps/employee/send_to_supvr',
    GETGoalLibrary: '/maps/employee/get_goal_lib',
    GETSession: '/maps/common/get_active_session',
    POSTSaveActivity: '/maps/employee/save_activity',
    POSTSaveAchievement: '/maps/employee/save_achievem',
    POSTUploadActivityAttachment: '/maps/employee/upload_acvy_att',
    POSTUploadAchievementAttachment: '/maps/employee/upload_achv_att',
    GETKpiList: '/maps/employee/get_kpi_list/',
    GETActivityList: '/maps/employee/get_activity_list/',
    GETAchievementList: '/maps/employee/get_achievem_list/',
    POSTDeleteActivity: '/maps/employee/delete_activity',
    POSTDeleteAchievement: '/maps/employee/delete_achievem',
    GETActivityById: '/maps/employee/get_activity_by_id/',
    GETAchievementById: '/maps/employee/get_achievem_by_id/',
    POSTEditActivity: '/maps/employee/edit_activity_by_id',
    POSTEditAchievement: '/maps/employee/edit_achievem_by_id',
    POSTActivityAttachmentUpload: '/maps/employee/save_activity_att',
    POSTAchievementAttachmentUpload: '/maps/employee/save_achievem_att',

    //supervisor
    GETEvaluationFormSupv: '/maps/supervisor/get_evaluation_form/', 
    GETViewFeedbackAsSupervisor: '/maps/supervisor/get_feedback_list',
    POSTRevertForm: '/maps/supervisor/revert_subor_form',
    POSTMapsApprove: '/maps/supervisor/approve',
    POSTGetDeliverableViewDetails: '/maps/supervisor/get_deliverable',
    POSTGetMidYearAppraiseeSupv: '/maps/supervisor/get_midyear_appraise_by_id_n_type',
    POSTGetEndYearAppraiseeSupv: '/maps/supervisor/get_yearend_appraise_by_id_n_type',
    POSTPostMidYearAppraiseeSupervisor: '/maps/supervisor/save_midyear_appraise',
    POSTPostEndYearAppraiseeSupervisor: '/maps/supervisor/save_yearend_appraise',
    POSTPostEndYearReviewer: '/maps/supervisor/approve_f',
    GETReviewerRatingAll: '/maps/employee/get_fnlrat_by_fmid/',
    POSTAwknowledgementEmp: '/maps/employee/acknowledge',
    POSTRequestFeedbackSup: '/maps/supervisor/request_feedback',
    GETViewFeedbackRequestSupv: '/maps/supervisor/get_feedback_list_by_spn/',
    POSTRequestFeedbackSupOnBehalf: '/maps/supervisor/request_feedback_ob',
    GETActivityListSupv: '/maps/supervisor/get_activity_list/',
    GETMyActivityListSupv: '/maps/supervisor/get_activity_list_self',
    GETAchievementListSupv: '/maps/supervisor/get_achievem_list/',
    GETMyAchievementListSupv: '/maps/supervisor/get_achievem_list_self',

});