
export const En = Object.freeze({
    lang: 'Bahasa',
    name: 'Nama',
    loading : 'Sila tunggu...', 
    yes: 'Ya',
    no: 'Tidak',
    back: 'Kembali',
    view : 'Lihat',
    confirm: 'Pasti',
    cancel: 'Batal',
    submit: 'Hantar',
    add: 'Tambah',
    edit: 'Sunting',
    complete: 'Selasai',
    acknowledge: 'Pengesahan',
    revert: 'Kembalikan',

    update: 'Kemas Kini',
    delete: 'Padam',
    download: "Lihat Dokumen",
    
    head_sub_title: '',
    pg_title: 'Voluntary Separation Plan (VSP) 2021',
    h3_subheader: 'VSP 2021',
    sec_title_greet: 'Selamat datang ke VSP 2021',
    sec_title_content1: 'Pastikan anda membaca dan memahami',
    sec_title_content2: 'terlebih dahulu sebelum memohon',
    tnc: 'Terma & Syarat',
    faq: 'Soalan-soalan Lazim',
    content_instruction: 'Sila pilih salah satu dari tarikh akhir perkhidmatan di bawah',
    content_applied: '',
    date: 'Tarikh',
    date_end_service: 'Tarikh Tamat Perkhidmatan',
    est_special_reward: 'Anggaran Ganjaran Khas',
    est_debt_bal: 'Anggaran Baki Hutang',
    apply: 'Mohon',
    not_interest: 'Tidak Berminat',
    saya: 'Saya',
    form_disclaimer1: 'ingin mengemukakan permohonan saya untuk menyertai Skim VSP 2021. Permohonan ini dibuat dengan atas kerelaan penuh saya sendiri dan tiada sebarang paksaan atau arahan mana-mana pihak.',
    form_disclaimer2: 'Saya sedia maklum bahawa pihak Syarikat mempunyai budibicara sepenuhnya untuk menerima atau menolak permohonan saya ini termasuklah menyesuaikan tarikh akhir perkhidmatan jika dirasakan perlu.',
    form_disclaimer3: 'Saya juga akur dan faham Ganjaran Khas yang akan diterima akan boleh dikenakan apa-apa cukai pendapatan di bawah perenggan 15 Jadual 6 Akta Cukai Pendapatan 1967 (ACP).',  
    from_check_disclaimer: 'Saya telah membaca, faham dan bersetuju dengan Terma dan Syarat VSP 2021',   
    form_label_verify_ic: 'Pengesahan No Kad Pengenalan', 

    applied: 'Sudah Dipohon',
    not_applied: 'x',
    disclaimer_doc: 'Semua maklumat yang terkandung dalam dokumen ini adalah sulit dan hanya untuk maklumat penerima yang telah dikenalpasti dan tidak boleh digunakan, diterbitkan atau diedarkan semula tanpa persetujuan bertulis dari pihak TM. Harap maklum bahawa sebarang kesalahan boleh dianggap melanggar dasar syarikat.',
});

export const My = Object.freeze({
    lang: 'Bahasa',
    name: 'Nama',
    loading : 'Sila tunggu...', 
    yes: 'Ya',
    no: 'Tidak',
    back: 'Kembali',
    view : 'Lihat',
    confirm: 'Pasti',
    cancel: 'Batal',
    submit: 'Hantar',
    add: 'Tambah',
    edit: 'Sunting',
    complete: 'Selasai',
    acknowledge: 'Pengesahan',
    revert: 'Kembalikan',

    update: 'Kemas Kini',
    delete: 'Padam',
    download: "Lihat Dokumen",
    
    head_sub_title: '',
    pg_title: 'Voluntary Separation Plan (VSP) 2021',
    h3_subheader: 'VSP 2021',
    sec_title_greet: 'Selamat datang ke VSP 2021',
    sec_title_content1: 'Pastikan anda membaca dan memahami',
    sec_title_content2: 'terlebih dahulu sebelum memohon',
    tnc: 'Terma & Syarat',
    faq: 'Soalan-soalan Lazim',
    content_instruction: 'Sila pilih salah satu dari tarikh akhir perkhidmatan di bawah',
    content_applied: '',
    date: 'Tarikh',
    date_end_service: 'Tarikh Tamat Perkhidmatan',
    est_special_reward: 'Anggaran Ganjaran Khas',
    est_debt_bal: 'Anggaran Baki Hutang',
    apply: 'Mohon',
    not_interest: 'Tidak Berminat',
    saya: 'Saya',
    form_disclaimer1: 'ingin mengemukakan permohonan saya untuk menyertai Skim VSP 2021. Permohonan ini dibuat dengan atas kerelaan penuh saya sendiri dan tiada sebarang paksaan atau arahan mana-mana pihak.',
    form_disclaimer2: 'Saya sedia maklum bahawa pihak Syarikat mempunyai budibicara sepenuhnya untuk menerima atau menolak permohonan saya ini termasuklah menyesuaikan tarikh akhir perkhidmatan jika dirasakan perlu.',
    form_disclaimer3: 'Saya juga akur dan faham Ganjaran Khas yang akan diterima akan boleh dikenakan apa-apa cukai pendapatan di bawah perenggan 15 Jadual 6 Akta Cukai Pendapatan 1967 (ACP).',  
    from_check_disclaimer: 'Saya telah membaca, faham dan bersetuju dengan Terma dan Syarat VSP 2021',   
    form_label_verify_ic: 'Pengesahan No Kad Pengenalan',   

    applied: 'Sudah Dipohon',
    not_applied: 'x',
    disclaimer_doc: 'Semua maklumat yang terkandung dalam dokumen ini adalah sulit dan hanya untuk maklumat penerima yang telah dikenalpasti dan tidak boleh digunakan, diterbitkan atau diedarkan semula tanpa persetujuan bertulis dari pihak TM. Harap maklum bahawa sebarang kesalahan boleh dianggap melanggar dasar syarikat.',
    
});
